### ISSUE TITLE
Invalid code of autohack?

### ISSUE THREAD

**Issue by AlpJust** [salmon85/Grey_hack_scripts#1]
Is everything allwright with autohack code? I have the all the "{home_dir}/src/includes/"
I changed "import_code("/home/salmon/src/includes/json.src")" to "import_code("/home/alp/src/includes/json.src")"
And script doesn't work. Do i doing something wrong?
![image](https://github.com/salmon85/Grey_hack_scripts/assets/74210310/9fa8e093-f300-4f0a-b189-2b276f96eb78)
![image](https://github.com/salmon85/Grey_hack_scripts/assets/74210310/2a65ae8a-25e1-4bb3-9bde-2241b640411a)
And yes, i didn't change something else.
Oh, and here is my libraries
![image](https://github.com/salmon85/Grey_hack_scripts/assets/74210310/ca6c6068-95ea-4928-8bcc-4e79e9b4e5f0)

**Comment by salmon85** [comment]
Humm, this bug again.

This is where the script is failing to pull the cache or acknowledge there is no cache but continuing as if it's loaded one.

Did you choose to use the cache?
If you did, do you have SSH access to the server you chose?
Has the server been setup as a cache (with the --setup-server (if you're local on the server) or --setup-server-remote (for remote setup (assuming the server has working ssh setup already))

I've not added any checks to the script yet that absolutely double checks it's got data in the memorys.



Try the new upload to github for autohack, I just checked my vscode, and it looks like I may have forgotten to commit the file
